# Generated by Django 3.1.2 on 2020-10-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='kind',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Parrot', 'Parrot')], max_length=10, null=True),
        ),
    ]
